/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Spreadsheet.Builder.k

import builders.dsl.spreadsheet.builder.poi.PoiSpreadsheetBuilder

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    val file = java.io.File("spreadsheet.xlsx")
    PoiSpreadsheetBuilder.create(file).build { w ->
        w.sheet("Sample") { s ->
            s.row {r ->
                r.cell("A");
            }
        }
    }
}
